# Copyright Bruno Dutra 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp   
os: linux
sudo: required

env:
     matrix:
        # - COMPILER=g++       COMPILER_VERSION=4.7
        - COMPILER=g++      COMPILER_VERSION=4.8
        - COMPILER=g++      COMPILER_VERSION=4.9
        - COMPILER=clang    COMPILER_VERSION=3.2
        - COMPILER=clang    COMPILER_VERSION=3.3
        - COMPILER=clang    COMPILER_VERSION=3.4
        - COMPILER=clang    COMPILER_VERSION=3.5
        - COMPILER=clang    COMPILER_VERSION=3.6
        - COMPILER=clang    COMPILER_VERSION=3.7
    
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:h-rayflood/llvm
    - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
    - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get -qq update
    
install:
    - sudo apt-get -qq install ${COMPILER}-${COMPILER_VERSION}

before_script:
    - mkdir build
    - cd build
    - if [ "$COMPILER" == "g++" ]; then (export CXX=g++ && cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-${COMPILER_VERSION} -DBOOST_MPL2_ENABLE_EXTRA_WARNINGS=ON -DBOOST_MPL2_ENABLE_STRICT_BEHAVIOR=OFF -DBOOST_MPL2_ENABLE_CXX11=ON -DBOOST_MPL2_ENABLE_CXX14=OFF -DBOOST_MPL2_ENABLE_GNU_DIALECTS=ON); fi
    - if [ "$COMPILER" == "clang" ]; then (export CXX=clang++ && cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${COMPILER_VERSION} -DBOOST_MPL2_ENABLE_EXTRA_WARNINGS=ON -DBOOST_MPL2_ENABLE_STRICT_BEHAVIOR=OFF -DBOOST_MPL2_ENABLE_CXX11=ON -DBOOST_MPL2_ENABLE_CXX14=ON -DBOOST_MPL2_ENABLE_GNU_DIALECTS=ON); fi
    
script:
    - make tests