# Copyright Bruno Dutra 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp
os: linux
sudo: false

matrix:
    include:
      - compiler: g++
        env: CXX_VERSION=4.8
        addons:
            apt:
                packages:
                  - g++-4.8
                sources: &sources
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise
                  - llvm-toolchain-precise-3.5
                  - llvm-toolchain-precise-3.6
                  - llvm-toolchain-precise-3.7

      - compiler: g++
        env: CXX_VERSION=4.9
        addons:
            apt:
                packages:
                  - g++-4.9
                sources: *sources

      - compiler: g++
        env: CXX_VERSION=5
        addons:
            apt:
                packages:
                  - g++-5
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.3
        addons:
            apt:
                packages:
                  - clang-3.3
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.4
        addons:
            apt:
                packages:
                  - clang-3.4
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.5
        addons:
            apt:
                packages:
                  - clang-3.5
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.6
        addons:
            apt:
                packages:
                  - clang-3.6
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.7
        addons:
            apt:
                packages:
                  - clang-3.7
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.8
        addons:
            apt:
                packages:
                  - clang-3.8
                sources: *sources

env:
    global:
      - secure: "DuBGzmeKiWMm5m0+uZhutjzCffB2PbixmuMm3IZWUi7/uAam4PPI37oeqVTIytxxfpgRvfR2ah75eJyU6ab72MBoHxGkHem10RAvhC/vPYbLZu545qfSGatyTI9R6NfERUxi7YIxjs6D8c4D/5k3gMoCbMUkU1Lze1708lknh5U="

    matrix:
      - BUILD_DOC=true

compiler: g++

install:
  - DEPS_PATH="${TRAVIS_BUILD_DIR}/deps"
  - mkdir "${DEPS_PATH}"

  - DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.linux.bin.tar.gz"
  - if [[ "${BUILD_DOC}" == "true" ]]; then mkdir "${DEPS_PATH}/doxygen" && travis_retry wget --quiet -O - ${DOXYGEN_URL} | tar --strip-components=1 -xz -C "${DEPS_PATH}/doxygen"; fi
  - if [[ "${BUILD_DOC}" == "true" ]]; then export PATH=${DEPS_PATH}/doxygen/bin:${PATH}; fi

before_script:
  - git config --global user.name "Travis Bot"
  - git config --global user.email "\<\>"

  - mkdir "${TRAVIS_BUILD_DIR}/build"
  - cd "${TRAVIS_BUILD_DIR}/build"

  - if [[ -n "${CXX_VERSION}" ]]; then CXX=${CXX}-${CXX_VERSION}; fi
  - cmake "${TRAVIS_BUILD_DIR}" -DCMAKE_CXX_COMPILER=/usr/bin/${CXX}

script:
  - if [[ "${BUILD_DOC}" != "true" ]]; then time make metal && ctest --output-on-failure; fi
  - if [[ "${BUILD_DOC}" == "true" && "${TRAVIS_PULL_REQUEST}" != "true" && "${TRAVIS_BRANCH}" == "master" ]]; then make metal.doc.update &> /dev/null; fi
  - if [[ "${BUILD_DOC}" == "true" && ("${TRAVIS_PULL_REQUEST}" == "true" || "${TRAVIS_BRANCH}" != "master") ]]; then time make metal.doc; fi
