# Copyright Bruno Dutra 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

os: Visual Studio 2015
platform: Any CPU
clone_depth: 1

matrix:
    allow_failures:
      - GENERATOR: "Visual Studio 12 2013 Win64"

environment:
    matrix:
      - GENERATOR: "Visual Studio 12 2013 Win64"
      - GENERATOR: "Visual Studio 14 2015 Win64"
      - GENERATOR: "MinGW Makefiles"

before_build:
  - git submodule update --init --recursive

  - set PATH=%PATH:Git\bin=%;C:\MinGW\bin

  - mkdir "%APPVEYOR_BUILD_FOLDER%\build"
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - cmake -G"%GENERATOR%" "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - cmake --build "%APPVEYOR_BUILD_FOLDER%\build" --target metal.test

test_script:
  - ctest --output-on-failure
