# Copyright Bruno Dutra 2015-2016
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt

shallow_clone: true

environment:
    matrix:
      - BUILD_DOC: true
      - GENERATOR: "MinGW Makefiles"
      - GENERATOR: "NMake Makefiles"
        COMPILER: cl

configuration:
  - Debug

install:
  - if "%BUILD_DOC%" equ "true" (choco install doxygen.portable)

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

  - set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%

  - set "METAL_SOURCE_PATH=%APPVEYOR_BUILD_FOLDER%"

  - set "METAL_BUILD_PATH=%APPVEYOR_BUILD_FOLDER%\build"
  - mkdir "%METAL_BUILD_PATH%"

  - set "CMAKE_ARGS=-DCMAKE_BUILD_TYPE=%CONFIGURATION%"
  - if defined COMPILER (set "CMAKE_ARGS=-DCMAKE_CXX_COMPILER=%COMPILER% %CMAKE_ARGS%")
  - if defined GENERATOR (set "CMAKE_ARGS=-G"%GENERATOR%" %CMAKE_ARGS%")
  - pushd "%METAL_BUILD_PATH%" && cmake "%METAL_SOURCE_PATH%" %CMAKE_ARGS% & popd

build_script:
  - if "%BUILD_DOC%" equ "true" (
        cmake --build "%METAL_BUILD_PATH%" --target doc --config "%CONFIGURATION%"
    ) else (
        pushd "%METAL_BUILD_PATH%" && ctest -C "%CONFIGURATION%" --output-on-failure & popd
    )
