# Copyright Bruno Dutra 2015-2017
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt

shallow_clone: true

environment:
    matrix:
      - BUILD_DOC: true

      - GENERATOR: "Visual Studio 14 2015"
        CXXFLAGS: /DMETAL_TEST_GEN_LIMIT=7

      - GENERATOR: "MinGW Makefiles"
        CXXFLAGS: -DMETAL_TEST_GEN_LIMIT=9

configuration:
  - Debug

install:
  - if "%BUILD_DOC%" equ "true" (choco install doxygen.portable)

before_build:
  - set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%

  - set "METAL_SOURCE_PATH=%APPVEYOR_BUILD_FOLDER%"
  - set "METAL_BUILD_PATH=%APPVEYOR_BUILD_FOLDER%\build"
  - mkdir "%METAL_BUILD_PATH%"

  - set "CMAKE_ARGS=%METAL_SOURCE_PATH%"
  - if defined GENERATOR (set "CMAKE_ARGS=%CMAKE_ARGS% -G"%GENERATOR%"")
  - set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBOOST_ROOT=C:\Libraries\boost"
  - pushd "%METAL_BUILD_PATH%" && cmake %CMAKE_ARGS% & popd

build_script:
  - if "%BUILD_DOC%" equ "true" (
        cmake --build "%METAL_BUILD_PATH%" --target doc --config "%CONFIGURATION%"
    ) else (
        pushd "%METAL_BUILD_PATH%" && ctest -C "%CONFIGURATION%" --output-on-failure & popd
    )
